name: CI

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: List files
        run: ls -R

      - name: Run Tests
        run: node test.js

      # - name: SonarQube Scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #   run: |
      #     npx sonar-scanner \
      #       -Dsonar.projectKey=rsa_sonarqubw \
      #       -Dsonar.sources=. \
      #       -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine version tag
        id: version
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "Latest tag: $LATEST_TAG"

          if [ -z "$LATEST_TAG" ]; then
            BUMP_TAG="0.0.1"
          else          
            BUMP_TAG=$(echo $LATEST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          fi

          echo "New version tag: $BUMP_TAG"
          echo $BUMP_TAG > bump_tag.txt
          echo "BUMP_TAG=$BUMP_TAG" >> $GITHUB_ENV

      - name: Upload BUMP_TAG as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: bump-tag
          path: bump_tag.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t hardiksharma15jan/rsa_group:${{ env.BUMP_TAG }} .
          docker push hardiksharma15jan/rsa_group:${{ env.BUMP_TAG }}
          docker tag hardiksharma15jan/rsa_group:${{ env.BUMP_TAG }} hardiksharma15jan/rsa_group:latest
          docker push hardiksharma15jan/rsa_group:latest
